#filtering parameters
averaging_kernel_size: (5,5)
gauss_kernel_size: 3,3
dilate_kernel_size: (5,5)
sigmaX: 0

#contour parameters
contour_color: 0,129,255
min_contour_area: 3000

#Canny edge parameters
canny_low_threshold: 75
canny_high_threshold: 150