
# color thresholds
low_green: [36, 25, 25]
high_green: [70, 255, 255]

# parameters for Hough Lines Point Set
max_vote: 0
num_strips: 60
lines_max: 10
threshold: 5
min_rho: 0
max_rho: 1000
rho_step: 1