### number of lines from both positive and negative slope groups
num_of_lines: 5

gaussian_blur_kernel: 3
morph_kernel: 5

### how many pixels between each line
pixel_gap: 15
### the percentage of width we don't want 
bounding_box_x: 0.3

### percentage of height we don't want
bounding_box_y: 0.52

### how many points to draw lines from
points_per_line_side: 10
points_per_line_bottom: 15

### what is the minimum pixel length for a line
#min_line_length: 400