<?xml version='1.0'?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="camera_width" value="0.02"/>
  <xacro:property name="camera_length" value="0.02"/>
  <xacro:property name="camera_height" value="0.01"/>
  <xacro:property name="camera_mass" value="0.01"/>
  <xacro:property name="chassis_width" value="0.65"/>
  <xacro:property name="chassis_length" value="1"/>
  <xacro:property name="chassis_height" value="0.05"/>
  <xacro:property name="chassis_mass" value="1.0"/>
  <xacro:property name="wheel_radius" value="0.0425"/>
  <xacro:property name="wheel_width" value="0.03"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  <xacro:property name="leg_length" value="0.05"/>
  <xacro:property name="leg_width" value="0.05"/>
  <xacro:property name="leg_height" value="0.75"/>
  <xacro:property name="leg_mass" value="0.4"/>

  <xacro:include filename="$(find agrobot)/urdf/macros.xacro"/>
  <xacro:include filename="$(find agrobot)/urdf/materials.xacro"/>

  <link name='chassis'>
    <xacro:box_inertial name="chassis" m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
    <collision name='chassis_collision'>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>
    </link>


  <link name='wheel_FL'>
    <xacro:cylinder_inertial name="wheel_FL" m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    <collision name='wheel_FL_collision'>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>    
       <mesh>
            <uri>model://tire/meshes/tire.dae</uri>
        </mesh>
    </collision>
    <visual name='wheel_FL_visual'>
      <geometry>
        <mesh>
            <uri>model://tire/meshes/tire.dae</uri>
        </mesh>
        <!-- <cylinder radius="${wheel_radius}" length="${wheel_width}"/> -->
      </geometry>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
    </visual>
  </link>


  <joint name="wheel_FL_joint" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_FL"/>
    <origin xyz="${chassis_length/2-wheel_radius} ${chassis_width/2+wheel_width/2} ${chassis_height/2 + wheel_radius*2.1}"
            rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>
