agrobot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  wheel_FL_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_FL_position_joint
    pid: {p: 50, i: 0.01, d: 10.0}

  wheel_FL_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_FL_velocity_joint
    pid: {p: 1, i: 0.0, d: 0.0}

  wheel_FR_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_FR_position_joint
    pid: {p: 50, i: 0.01, d: 10.0}

  wheel_FR_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_FR_velocity_joint
    pid: {p: 1, i: 0.0, d: 0.0}

  wheel_BL_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_BL_position_joint
    pid: {p: 50, i: 0.01, d: 10.0}

  wheel_BL_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_BL_velocity_joint
    pid: {p: 1, i: 0.0, d: 0.0}

  wheel_BR_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel_BR_position_joint
    pid: {p: 50, i: 0.01, d: 10.0}

  wheel_BR_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_BR_velocity_joint
    pid: {p: 1, i: 0.0, d: 0.0}
  
  