name: Format python code
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
    - name: autopep8
      id: autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --recursive --in-place --aggressive --aggressive .
    - name: Fail if autopep8 made changes
      if: steps.autopep8.outputs.exit-code == 2
      run: exit 1