name: build-test

on: [pull_request_target]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: PEP8 Action
      uses: quentinguidee/pep8-action@v2.0.13-dev
      with:
        token: ${{ secrets.GITHUB_TOKEN }}