name: build-test
on: [push, pull_request]
jobs:
  pep-check:
    name: pep-check
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
        ref: ${{ github.event.pull_request.head.sha }}
      - name: 'Run PEP8'
        uses: quentinguidee/pep8-action@v1
        with:
          arguments: '--max-line-length=120'